### ISSUE TITLE
why upgrade to go 1.16? 

### ISSUE THREAD

**Issue by nevernet** [sunshineplan/imgconv#1]
:)

**Comment by sunshineplan** [comment]
Sorry, I didn't turn on the notification so I just saw it. The upgrade did not consider a lot, just to develop some good code habits, so I upgraded to the latest version. The new version replaces most of the functions under ioutil with os or io.
I am very sorry if this causes you inconvenience, but I believe that upgrading the go version should not be too troublesome.

**Comment by nevernet** [comment]
thank for your reply :) 
dont worry
