### ISSUE TITLE
merge jpg to pdf use case

### ISSUE THREAD

**Issue by gedw99** [sunshineplan/imgconv#114]
when I scan papers using my iPhone camera, I need to take the many images and merge them into 1 PDF on my Mac laptop.

I scan them int my ICLOUD drive and so they are available on my MAC a second later.

so, I was wondering if merging is possible via the config ?

This one works but only does a 1 for 1 conversion using this test data, which is NOT what I need:

**My Test data**

in folder:
image-001.jpg
image-002.jpg

out folder:
image-001. pd
 image-002.pdf

**My config.ini**

```sh
src=.data/in
dst=.data/out
quality=75
opacity=100
random=true
percent=50
worker=5
format=pdf
```

What I wanted is to convert  all the .jpgs into a single pdf. 

If this does not yet exist let me know, as I think it's a common use case.

**Comment by sunshineplan** [comment]
If you can write Golang code, you can use the EncodeFile method in the github.com/sunshineplan/pdf package to write multiple jpeg files into one pdf file.

**Comment by gedw99** [comment]
yep thats why I figured

do you want a PR with a config to drive it ?

**Comment by sunshineplan** [comment]
Considering that the converter mainly utilizes the functionality of imgconv and src can include subfolders, while merging is only supported for the pdf format, the implementation would involve complex considerations. Therefore, supporting pdf merging is not planned.

**Comment by gedw99** [comment]
That’s what I thought. Good to know where it stands.

I will fork and update the code and config so it’s possible using a queue.
