### ISSUE TITLE
Webb encoder with no cgo

### ISSUE THREAD

**Issue by gedw99** [sunshineplan/imgconv#116]
https://git.sr.ht/~jackmordaunt/go-libwebp

It’s usable . I used it on another project.

its a pure golang Webp encode and decode package .

**Comment by sunshineplan** [comment]
Thanks for the suggestion! I appreciate you bringing this package to my attention. 
I'm currently focusing on using the official `golang.org/x/image` library for image processing. This decision was made to ensure stability and minimize maintenance overhead. I'm committed to maintaining a streamlined and efficient codebase.
I'll keep your suggestion in mind for future considerations. If there are any other feedback or feature requests you'd like to share, I'm always open to hearing them.
