### ISSUE TITLE
It is possible to convert png to jpeg leaving the white background?

### ISSUE THREAD

**Issue by lockiie** [sunshineplan/imgconv#36]
When I convert png to jpeg and this image has a transparent background, after converting the transparent one becomes black, it is possible to leave the transparent white.

**Comment by sunshineplan** [comment]
Refer: https://www.socketloop.com/tutorials/golang-convert-png-transparent-background-image-to-jpg-or-jpeg-image
Lately, I will try to add an option to set up a background color for transparent image.

**Comment by lockiie** [comment]
Thank you very much for the answer, the example you sent me worked. God bless you.

**Comment by sunshineplan** [comment]
[v1.1.3](https://github.com/sunshineplan/imgconv/releases/tag/v1.1.3) @lockiie
You can use BackgroundColor EncodeOption to set background color.
Or using --white-background flag to set white background color when using converter.
